// Generated by build.py — do not edit
const BUILD_VERSION = '3edfb87c4603';
const SHELL_CACHE = 'kartomat-shell-3edfb87c4603';
const ASSET_CACHE = 'kartomat-assets';

const PRECACHE = [
  './index.html',
  'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js',
  './manifest.json',
  './dist/icons/icon-192.png',
  './dist/icons/icon-512.png',
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then(cache => cache.addAll(PRECACHE))
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== SHELL_CACHE && k !== ASSET_CACHE).map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Supabase bucket assets (background, font) → runtime cache-first
  // Match by path since the Supabase origin is runtime config, not known at build time
  if (url.pathname.includes('/storage/v1/object/public/') && url.pathname.includes('/assets/')) {
    event.respondWith(
      caches.match(request).then(cached => {
        if (cached) return cached;
        return fetch(request).then(response => {
          caches.open(ASSET_CACHE).then(cache => cache.put(request, response.clone()));
          return response;
        });
      })
    );
    return;
  }

  // Other Supabase requests (gallery, publish, delete) → network-only; fail gracefully offline
  if (url.pathname.includes('/rest/v1/') || url.pathname.includes('/storage/v1/') ||
      url.pathname.includes('/auth/v1/') || url.pathname.includes('/functions/v1/')) {
    return;
  }

  // Shell + CDN → cache-first
  event.respondWith(
    caches.match(request).then(cached => cached || fetch(request))
  );
});
